version: "3"

services:
  postgres:
    container_name: easyrp
    image: "postgres:11.5"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: easyrpdb
      POSTGRES_PASSWORD: unlocked
    expose:
      - "5432"
    ports:
      - "5432:5432"