export const accountPlanData = [
  {
    name: 'optimizing',
    description: 'Configurable leading edge attitude',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Reverse-engineered',
    description: 'Focused uniform core',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Ameliorated',
    description: 'Fully-configurable logistical collaboration',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'website',
    description: 'Operative solution-oriented portal',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'capacity',
    description: 'User-friendly global frame',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'neutral',
    description: 'Multi-lateral background productivity',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'monitoring',
    description: 'Reduced dynamic structure',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Assimilated',
    description: 'Managed multimedia implementation',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'static',
    description: 'Virtual empowering Graphical User Interface',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'empowering',
    description: 'Total real-time Graphic Interface',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'clear-thinking',
    description: 'Decentralized logistical definition',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'bandwidth-monitored',
    description: 'User-friendly multimedia Graphic Interface',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'neutral',
    description: 'Managed bandwidth-monitored function',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'capacity',
    description: 'Secured object-oriented pricing structure',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'frame',
    description: 'Down-sized client-driven access',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'emulation',
    description: 'Persistent client-server matrices',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Multi-layered',
    description: 'Balanced disintermediate strategy',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Diverse',
    description: 'Digitized clear-thinking paradigm',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'real-time',
    description: 'Open-source foreground benchmark',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'workforce',
    description: 'Decentralized 5th generation implementation',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Distributed',
    description: 'Polarised upward-trending system engine',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'solution-oriented',
    description: 'Compatible interactive access',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'ability',
    description: 'Optimized demand-driven toolset',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'didactic',
    description: 'Configurable executive knowledge user',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Realigned',
    description: 'Front-line 4th generation access',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'moratorium',
    description: 'Team-oriented solution-oriented encoding',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Profound',
    description: 'Multi-channelled scalable access',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Function-based',
    description: 'Innovative analyzing product',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'functionalities',
    description: 'Universal logistical conglomeration',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'fresh-thinking',
    description: 'Public-key modular workforce',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Robust',
    description: 'De-engineered reciprocal paradigm',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'software',
    description: 'Intuitive explicit support',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Persistent',
    description: 'Universal scalable productivity',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'hardware',
    description: 'Multi-lateral fault-tolerant benchmark',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'budgetary management',
    description: 'Secured bifurcated strategy',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'dedicated',
    description: 'Down-sized static circuit',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'projection',
    description: 'Stand-alone dedicated focus group',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'conglomeration',
    description: 'Quality-focused 24 hour pricing structure',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'algorithm',
    description: 'Compatible attitude-oriented budgetary management',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'support',
    description: 'Object-based didactic help-desk',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'encryption',
    description: 'Multi-layered local parallelism',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'uniform',
    description: 'Right-sized disintermediate Graphic Interface',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Fully-configurable',
    description: 'Realigned upward-trending paradigm',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Customer-focused',
    description: 'Inverse national intranet',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'throughput',
    description: 'Networked analyzing website',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Down-sized',
    description: 'Cross-platform foreground info-mediaries',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'challenge',
    description: 'Programmable holistic interface',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'open system',
    description: 'Networked holistic orchestration',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'project',
    description: 'Customer-focused fresh-thinking open architecture',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'info-mediaries',
    description: 'Extended tertiary info-mediaries',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'help-desk',
    description: 'Fundamental non-volatile knowledge user',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Reverse-engineered',
    description: 'Implemented full-range project',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Cloned',
    description: 'Integrated heuristic success',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'projection',
    description: 'Integrated motivating strategy',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'challenge',
    description: 'Re-engineered attitude-oriented firmware',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'directional',
    description: 'Up-sized background product',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'encoding',
    description: 'Reduced full-range attitude',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Enhanced',
    description: 'Inverse coherent core',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'open architecture',
    description: 'Customer-focused well-modulated pricing structure',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'system-worthy',
    description: 'Realigned bi-directional budgetary management',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'system-worthy',
    description: 'Persevering executive infrastructure',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Advanced',
    description: 'Customer-focused dynamic alliance',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'intranet',
    description: 'Triple-buffered dynamic architecture',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Business-focused',
    description: 'Multi-lateral context-sensitive budgetary management',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'clear-thinking',
    description: 'Sharable interactive model',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'intangible',
    description: 'Enterprise-wide user-facing moderator',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'multi-state',
    description: 'Secured client-driven interface',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'initiative',
    description: 'De-engineered needs-based extranet',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Seamless',
    description: 'Self-enabling coherent budgetary management',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Universal',
    description: 'User-friendly zero tolerance pricing structure',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'modular',
    description: 'Public-key bi-directional projection',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'secondary',
    description: 'Distributed 3rd generation application',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'User-friendly',
    description: 'Pre-emptive systemic array',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'knowledge user',
    description: 'Balanced transitional knowledge base',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Reverse-engineered',
    description: 'Self-enabling directional function',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'bandwidth-monitored',
    description: 'Reactive composite secured line',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'non-volatile',
    description: 'De-engineered incremental access',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'secured line',
    description: 'Streamlined even-keeled forecast',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Intuitive',
    description: 'Public-key system-worthy hardware',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Right-sized',
    description: 'Synchronised uniform service-desk',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'parallelism',
    description: 'Multi-lateral transitional Graphical User Interface',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'service-desk',
    description: 'Multi-tiered neutral collaboration',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'disintermediate',
    description: 'Function-based directional website',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'well-modulated',
    description: 'Public-key attitude-oriented artificial intelligence',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'time-frame',
    description: 'Quality-focused encompassing hub',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Enhanced',
    description: 'Fully-configurable stable complexity',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'array',
    description: 'Total analyzing structure',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'orchestration',
    description: 'Multi-layered eco-centric time-frame',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Programmable',
    description: 'Inverse high-level interface',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'encoding',
    description: 'Face to face asynchronous array',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'algorithm',
    description: 'Seamless systematic encoding',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'installation',
    description: 'Reactive encompassing software',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'dedicated',
    description: 'Upgradable intermediate paradigm',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'empowering',
    description: 'Multi-channelled real-time functionalities',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Upgradable',
    description: 'Proactive neutral adapter',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'hardware',
    description: 'Function-based actuating firmware',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'bifurcated',
    description: 'Profound cohesive conglomeration',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Visionary',
    description: 'Customer-focused 24 hour monitoring',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'attitude-oriented',
    description: 'Up-sized leading edge standardization',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'projection',
    description: 'Up-sized multi-state hierarchy',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'application',
    description: 'Decentralized clear-thinking service-desk',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'bi-directional',
    description: 'Grass-roots secondary migration',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Persistent',
    description: 'Upgradable mission-critical matrices',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'homogeneous',
    description: 'Cloned fresh-thinking emulation',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'motivating',
    description: 'Robust intermediate algorithm',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Optimized',
    description: 'Enterprise-wide logistical standardization',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'open system',
    description: 'Integrated dynamic throughput',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'multi-tasking',
    description: 'Visionary well-modulated firmware',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Open-architected',
    description: 'Assimilated 5th generation moratorium',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'superstructure',
    description: 'Down-sized tertiary database',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'zero tolerance',
    description: 'Open-source secondary data-warehouse',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'intermediate',
    description: 'Progressive fresh-thinking product',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'intermediate',
    description: 'Organic local model',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'background',
    description: 'Automated homogeneous secured line',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'executive',
    description: 'Extended uniform secured line',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'directional',
    description: 'Reduced scalable toolset',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: '3rd generation',
    description: 'Profound full-range strategy',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Balanced',
    description: 'Open-source coherent portal',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'access',
    description: 'Vision-oriented neutral concept',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'optimizing',
    description: 'Multi-lateral zero defect complexity',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'impactful',
    description: 'Centralized needs-based info-mediaries',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'executive',
    description: 'Enterprise-wide web-enabled data-warehouse',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'instruction set',
    description: 'Proactive asynchronous core',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Persevering',
    description: 'Multi-channelled well-modulated help-desk',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'interactive',
    description: 'Monitored local implementation',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'contextually-based',
    description: 'Robust radical budgetary management',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Reverse-engineered',
    description: 'Organized multi-tasking installation',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'incremental',
    description: 'Centralized systematic encoding',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Total',
    description: 'Persistent 24 hour access',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'access',
    description: 'Devolved impactful strategy',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Monitored',
    description: 'Right-sized zero administration open system',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'zero administration',
    description: 'Re-contextualized multi-state parallelism',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Multi-channelled',
    description: 'Centralized motivating adapter',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'analyzer',
    description: 'Expanded solution-oriented encoding',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Innovative',
    description: 'Diverse bottom-line encoding',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'circuit',
    description: 'Upgradable homogeneous firmware',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Reduced',
    description: 'Reduced heuristic interface',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Customizable',
    description: 'Reverse-engineered executive open system',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Proactive',
    description: 'Versatile 6th generation alliance',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'internet solution',
    description: 'Horizontal content-based local area network',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'object-oriented',
    description: 'Diverse composite array',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Configurable',
    description: 'Balanced attitude-oriented intranet',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'strategy',
    description: 'Switchable value-added benchmark',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Function-based',
    description: 'Adaptive explicit project',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'disintermediate',
    description: 'Secured 3rd generation archive',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Versatile',
    description: 'Secured national attitude',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'mobile',
    description: 'Balanced needs-based customer loyalty',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'groupware',
    description: 'Visionary foreground emulation',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'asymmetric',
    description: 'Quality-focused user-facing initiative',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'multi-tasking',
    description: 'Cloned 24 hour orchestration',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'mobile',
    description: 'Synchronised motivating functionalities',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'intangible',
    description: 'Grass-roots maximized service-desk',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'approach',
    description: 'Persevering stable encoding',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'implementation',
    description: 'Polarised zero defect contingency',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'implementation',
    description: 'Robust systemic neural-net',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Cloned',
    description: 'Configurable explicit encoding',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'circuit',
    description: 'Multi-tiered upward-trending approach',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Innovative',
    description: 'Front-line dynamic functionalities',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'implementation',
    description: 'Realigned disintermediate structure',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Synergistic',
    description: 'Realigned composite synergy',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'optimizing',
    description: 'Future-proofed eco-centric structure',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'model',
    description: 'Organized encompassing firmware',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'installation',
    description: 'Organized bi-directional encryption',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'benchmark',
    description: 'Multi-tiered methodical task-force',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'solution-oriented',
    description: 'Adaptive regional secured line',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'productivity',
    description: 'Cloned heuristic toolset',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'groupware',
    description: 'Cross-group multimedia moratorium',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'clear-thinking',
    description: 'Programmable bottom-line encryption',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'clear-thinking',
    description: 'Open-source multi-tasking open architecture',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'capability',
    description: 'User-centric 6th generation concept',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'software',
    description: 'Digitized next generation moderator',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'client-driven',
    description: 'Synchronised coherent attitude',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'foreground',
    description: 'Robust mission-critical forecast',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'needs-based',
    description: 'Monitored real-time emulation',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Operative',
    description: 'Advanced local internet solution',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Up-sized',
    description: 'Persevering zero administration superstructure',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Cross-platform',
    description: 'Virtual impactful artificial intelligence',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Optimized',
    description: 'Phased explicit moratorium',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'access',
    description: 'Enhanced solution-oriented projection',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'dedicated',
    description: 'Persistent maximized core',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'client-driven',
    description: 'Reverse-engineered human-resource emulation',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Function-based',
    description: 'Balanced transitional alliance',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'impactful',
    description: 'Profound stable process improvement',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'responsive',
    description: 'Face to face bottom-line leverage',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Re-contextualized',
    description: 'Decentralized zero tolerance toolset',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'capability',
    description: 'Object-based composite concept',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Profit-focused',
    description: 'Ameliorated demand-driven analyzer',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'attitude',
    description: 'Self-enabling logistical focus group',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'demand-driven',
    description: 'Networked didactic framework',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Advanced',
    description: 'Pre-emptive responsive alliance',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'disintermediate',
    description: 'Up-sized neutral intranet',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'high-level',
    description: 'Front-line zero administration portal',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'Focused',
    description: 'Grass-roots asynchronous approach',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'matrix',
    description: 'Switchable maximized open system',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Decentralized',
    description: 'Monitored non-volatile access',
    costType: 'INCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'dynamic',
    description: 'Automated dedicated archive',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'Grass-roots',
    description: 'Implemented mission-critical matrices',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'solution-oriented',
    description: 'Multi-layered leading edge portal',
    costType: 'OUTCOME',
    accountPlanType: 'FIXED',
  },
  {
    name: 'client-server',
    description: 'Cross-group high-level budgetary management',
    costType: 'OUTCOME',
    accountPlanType: 'VARIABLE',
  },
  {
    name: 'help-desk',
    description: 'Open-architected zero defect standardization',
    costType: 'INCOME',
    accountPlanType: 'VARIABLE',
  },
];
